// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: NetspeakService.proto
#ifndef GRPC_NetspeakService_2eproto__INCLUDED
#define GRPC_NetspeakService_2eproto__INCLUDED

#include "NetspeakService.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace netspeak {
namespace service {

class NetspeakService final {
 public:
  static constexpr char const* service_full_name() {
    return "netspeak.service.NetspeakService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Search(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest& request, ::netspeak::service::SearchResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::netspeak::service::SearchResponse>> AsyncSearch(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::netspeak::service::SearchResponse>>(AsyncSearchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::netspeak::service::SearchResponse>> PrepareAsyncSearch(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::netspeak::service::SearchResponse>>(PrepareAsyncSearchRaw(context, request, cq));
    }
    virtual ::grpc::Status GetCorpora(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest& request, ::netspeak::service::CorporaResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::netspeak::service::CorporaResponse>> AsyncGetCorpora(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::netspeak::service::CorporaResponse>>(AsyncGetCorporaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::netspeak::service::CorporaResponse>> PrepareAsyncGetCorpora(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::netspeak::service::CorporaResponse>>(PrepareAsyncGetCorporaRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Search(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest* request, ::netspeak::service::SearchResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Search(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::netspeak::service::SearchResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Search(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest* request, ::netspeak::service::SearchResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Search(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest* request, ::netspeak::service::SearchResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Search(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::netspeak::service::SearchResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Search(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::netspeak::service::SearchResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void GetCorpora(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest* request, ::netspeak::service::CorporaResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCorpora(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::netspeak::service::CorporaResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetCorpora(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest* request, ::netspeak::service::CorporaResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetCorpora(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest* request, ::netspeak::service::CorporaResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetCorpora(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::netspeak::service::CorporaResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetCorpora(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::netspeak::service::CorporaResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::netspeak::service::SearchResponse>* AsyncSearchRaw(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::netspeak::service::SearchResponse>* PrepareAsyncSearchRaw(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::netspeak::service::CorporaResponse>* AsyncGetCorporaRaw(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::netspeak::service::CorporaResponse>* PrepareAsyncGetCorporaRaw(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Search(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest& request, ::netspeak::service::SearchResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::netspeak::service::SearchResponse>> AsyncSearch(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::netspeak::service::SearchResponse>>(AsyncSearchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::netspeak::service::SearchResponse>> PrepareAsyncSearch(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::netspeak::service::SearchResponse>>(PrepareAsyncSearchRaw(context, request, cq));
    }
    ::grpc::Status GetCorpora(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest& request, ::netspeak::service::CorporaResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::netspeak::service::CorporaResponse>> AsyncGetCorpora(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::netspeak::service::CorporaResponse>>(AsyncGetCorporaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::netspeak::service::CorporaResponse>> PrepareAsyncGetCorpora(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::netspeak::service::CorporaResponse>>(PrepareAsyncGetCorporaRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Search(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest* request, ::netspeak::service::SearchResponse* response, std::function<void(::grpc::Status)>) override;
      void Search(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::netspeak::service::SearchResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Search(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest* request, ::netspeak::service::SearchResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Search(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest* request, ::netspeak::service::SearchResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Search(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::netspeak::service::SearchResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Search(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::netspeak::service::SearchResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void GetCorpora(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest* request, ::netspeak::service::CorporaResponse* response, std::function<void(::grpc::Status)>) override;
      void GetCorpora(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::netspeak::service::CorporaResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetCorpora(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest* request, ::netspeak::service::CorporaResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetCorpora(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest* request, ::netspeak::service::CorporaResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetCorpora(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::netspeak::service::CorporaResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetCorpora(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::netspeak::service::CorporaResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::netspeak::service::SearchResponse>* AsyncSearchRaw(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::netspeak::service::SearchResponse>* PrepareAsyncSearchRaw(::grpc::ClientContext* context, const ::netspeak::service::SearchRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::netspeak::service::CorporaResponse>* AsyncGetCorporaRaw(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::netspeak::service::CorporaResponse>* PrepareAsyncGetCorporaRaw(::grpc::ClientContext* context, const ::netspeak::service::CorporaRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Search_;
    const ::grpc::internal::RpcMethod rpcmethod_GetCorpora_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Search(::grpc::ServerContext* context, const ::netspeak::service::SearchRequest* request, ::netspeak::service::SearchResponse* response);
    virtual ::grpc::Status GetCorpora(::grpc::ServerContext* context, const ::netspeak::service::CorporaRequest* request, ::netspeak::service::CorporaResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Search() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Search(::grpc::ServerContext* /*context*/, const ::netspeak::service::SearchRequest* /*request*/, ::netspeak::service::SearchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSearch(::grpc::ServerContext* context, ::netspeak::service::SearchRequest* request, ::grpc::ServerAsyncResponseWriter< ::netspeak::service::SearchResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCorpora : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetCorpora() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetCorpora() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCorpora(::grpc::ServerContext* /*context*/, const ::netspeak::service::CorporaRequest* /*request*/, ::netspeak::service::CorporaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCorpora(::grpc::ServerContext* context, ::netspeak::service::CorporaRequest* request, ::grpc::ServerAsyncResponseWriter< ::netspeak::service::CorporaResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Search<WithAsyncMethod_GetCorpora<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Search() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::netspeak::service::SearchRequest, ::netspeak::service::SearchResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::netspeak::service::SearchRequest* request, ::netspeak::service::SearchResponse* response) { return this->Search(context, request, response); }));}
    void SetMessageAllocatorFor_Search(
        ::grpc::experimental::MessageAllocator< ::netspeak::service::SearchRequest, ::netspeak::service::SearchResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::netspeak::service::SearchRequest, ::netspeak::service::SearchResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Search(::grpc::ServerContext* /*context*/, const ::netspeak::service::SearchRequest* /*request*/, ::netspeak::service::SearchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Search(
      ::grpc::CallbackServerContext* /*context*/, const ::netspeak::service::SearchRequest* /*request*/, ::netspeak::service::SearchResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Search(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::netspeak::service::SearchRequest* /*request*/, ::netspeak::service::SearchResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetCorpora : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetCorpora() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::netspeak::service::CorporaRequest, ::netspeak::service::CorporaResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::netspeak::service::CorporaRequest* request, ::netspeak::service::CorporaResponse* response) { return this->GetCorpora(context, request, response); }));}
    void SetMessageAllocatorFor_GetCorpora(
        ::grpc::experimental::MessageAllocator< ::netspeak::service::CorporaRequest, ::netspeak::service::CorporaResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::netspeak::service::CorporaRequest, ::netspeak::service::CorporaResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetCorpora() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCorpora(::grpc::ServerContext* /*context*/, const ::netspeak::service::CorporaRequest* /*request*/, ::netspeak::service::CorporaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetCorpora(
      ::grpc::CallbackServerContext* /*context*/, const ::netspeak::service::CorporaRequest* /*request*/, ::netspeak::service::CorporaResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetCorpora(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::netspeak::service::CorporaRequest* /*request*/, ::netspeak::service::CorporaResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Search<ExperimentalWithCallbackMethod_GetCorpora<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Search<ExperimentalWithCallbackMethod_GetCorpora<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Search() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Search(::grpc::ServerContext* /*context*/, const ::netspeak::service::SearchRequest* /*request*/, ::netspeak::service::SearchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetCorpora : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetCorpora() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetCorpora() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCorpora(::grpc::ServerContext* /*context*/, const ::netspeak::service::CorporaRequest* /*request*/, ::netspeak::service::CorporaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Search() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Search(::grpc::ServerContext* /*context*/, const ::netspeak::service::SearchRequest* /*request*/, ::netspeak::service::SearchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSearch(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCorpora : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetCorpora() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetCorpora() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCorpora(::grpc::ServerContext* /*context*/, const ::netspeak::service::CorporaRequest* /*request*/, ::netspeak::service::CorporaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCorpora(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Search() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Search(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Search(::grpc::ServerContext* /*context*/, const ::netspeak::service::SearchRequest* /*request*/, ::netspeak::service::SearchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Search(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Search(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetCorpora : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetCorpora() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetCorpora(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetCorpora() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCorpora(::grpc::ServerContext* /*context*/, const ::netspeak::service::CorporaRequest* /*request*/, ::netspeak::service::CorporaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetCorpora(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetCorpora(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Search : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Search() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::netspeak::service::SearchRequest, ::netspeak::service::SearchResponse>(std::bind(&WithStreamedUnaryMethod_Search<BaseClass>::StreamedSearch, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Search() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Search(::grpc::ServerContext* /*context*/, const ::netspeak::service::SearchRequest* /*request*/, ::netspeak::service::SearchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSearch(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::netspeak::service::SearchRequest,::netspeak::service::SearchResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCorpora : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetCorpora() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::netspeak::service::CorporaRequest, ::netspeak::service::CorporaResponse>(std::bind(&WithStreamedUnaryMethod_GetCorpora<BaseClass>::StreamedGetCorpora, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetCorpora() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCorpora(::grpc::ServerContext* /*context*/, const ::netspeak::service::CorporaRequest* /*request*/, ::netspeak::service::CorporaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCorpora(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::netspeak::service::CorporaRequest,::netspeak::service::CorporaResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Search<WithStreamedUnaryMethod_GetCorpora<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Search<WithStreamedUnaryMethod_GetCorpora<Service > > StreamedService;
};

}  // namespace service
}  // namespace netspeak


#endif  // GRPC_NetspeakService_2eproto__INCLUDED
